// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEkNmxNYOG3hrgHp8b53ARMP56T6-yXZY',
    appId: '1:63343951833:web:9b0c0a5d89413e8b0de3c8',
    messagingSenderId: '63343951833',
    projectId: 'flutterfire-5e10c',
    authDomain: 'flutterfire-5e10c.firebaseapp.com',
    storageBucket: 'flutterfire-5e10c.appspot.com',
    measurementId: 'G-8MXDMBM01N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVMEbzBFO-e_zCsyoYQdjLZIrOWOpq2ww',
    appId: '1:63343951833:android:f3864744a413e17a0de3c8',
    messagingSenderId: '63343951833',
    projectId: 'flutterfire-5e10c',
    storageBucket: 'flutterfire-5e10c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDraqgVE1ga5qOqn0bNM6HMA4hFYnyv-vE',
    appId: '1:63343951833:ios:1f3461fcf687692c0de3c8',
    messagingSenderId: '63343951833',
    projectId: 'flutterfire-5e10c',
    storageBucket: 'flutterfire-5e10c.appspot.com',
    iosClientId: '63343951833-2gcr6b48jom39onpqofal94hcnanslo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDraqgVE1ga5qOqn0bNM6HMA4hFYnyv-vE',
    appId: '1:63343951833:ios:1f3461fcf687692c0de3c8',
    messagingSenderId: '63343951833',
    projectId: 'flutterfire-5e10c',
    storageBucket: 'flutterfire-5e10c.appspot.com',
    iosClientId: '63343951833-2gcr6b48jom39onpqofal94hcnanslo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire',
  );
}
